FROM spark:3.5.7-java17-python3

RUN python3 -m pip install --no-cache-dir jupyterlab ipykernel

WORKDIR /opt/spark/work-dir
EXPOSE 8888

CMD ["bash","-lc","python3 -m jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --ServerApp.token=spark --ServerApp.password='' --ServerApp.allow_remote_access=True --ServerApp.root_dir=/opt/spark/work-dir"]
